### ISSUE TITLE
Error with Unreal Engine 5.1.0

### ISSUE THREAD

**Issue by haunetal1990** [kaiheilos/Utilities#21]
Unreal Engine: 5.1.0
File: 
Áƒ*žøÿÿÿ                      Z   /Game/Blueprints/Configs/Cars/Mercedes/Mercedes-AMG_GT3_2020/Mercedes-AMG_GT3_2020_AIData  " €   .      6             –     6  ö                  ñçOƒÆ¥G”z^ë{Ž¡1                                             ÃÚ2m    ú  :                 þ      ÿÿÿÿÿÿÿÿZ   /Game/Blueprints/Configs/Cars/Mercedes/Mercedes-AMG_GT3_2020/Mercedes-AMG_GT3_2020_AIData ô^}‰   /Script/CoreUObject øI->   /Script/Rennsport —¯=ý
   CarAIData ‰xi§   Class twx‘   Default__CarAIData =í(å   Mercedes-AMG_GT3_2020_AIData Ãh})   Package sGˆ              ýÿÿÿ                         ýÿÿÿ                                        þÿÿÿ    ÿÿÿÿ              4                                                                      þÿÿÿÿÿÿÿ

Error:
System.IO.EndofStreamException: Unable to read beyond the end of the stream.
at System.IO._Error.EndofFile()
at System.IO.MemoryStream.InternalReadInt32()
at AssetParser.ReadFile.GetTheData(Stream input)
at AssetParser.ReadFile..ctor(Byte[] bytes, String fileName)
at AssetEditor.CoreClass.LoadFile(String LoadName)

**Comment by Organism5** [comment]
same problem in the UE5.3.2
